# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_flag', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Person')),
                ('rpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Rpi')),
            ],
        ),
    ]
