# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortag',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
