# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_sensortag_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortag',
            name='move_flag',
        ),
    ]
