# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_sensortag_move_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
