# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 05:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_state_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='datetime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='sensortag',
            name='datetime',
        ),
        migrations.AddField(
            model_name='sensortag',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 5, 22, 18, 526240)),
        ),
    ]
