# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20180307_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortag',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
