# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20180307_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
