# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20180307_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortag',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
