# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20180308_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='move_flag',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
