# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20180308_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
