# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_person_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('rpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='info.Rpi')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
