# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
