# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_heartbeat_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
