# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_person_ignore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortag',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
