# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20180320_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpi',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
